# -*- coding: utf-8 -*-
"""praktikumPython2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DdfeAVeFWcq9l5V0wYL3eEdzPE8KZJPI
"""

angka = 10            # int
angka_koma = 2.5      # float
kata = "Halo"         # string
buah = ["apel", "mangga", "jeruk"]   # list

print(type(angka))
print(type(angka_koma))
print(type(kata))
print(type(buah))

belanja = ["beras", "minyak", "telur"]
belanja.append("gula")
belanja.append("kopi")

print("Daftar Belanja:")
for item in belanja:
    print(item)

harga = {
    "beras": 12000,
    "minyak": 17000,
    "telur": 24000,
    "gula": 15000,
    "kopi": 20000
}

total = harga["beras"] + harga["minyak"] + harga["telur"] + harga["gula"] + harga["kopi"]
print("Total Harga:", total)

def lingkaran(r):
    luas = 3.14 * r * r
    keliling = 2 * 3.14 * r
    return luas, keliling

luas, keliling = lingkaran(7)
print("Luas:", luas)
print("Keliling:", keliling)

usia = int(input("Masukkan usia: "))

if usia >= 0 and usia <= 13:
    print("Anak")
elif usia >= 14 and usia <= 24:
    print("Remaja")
elif usia >= 25 and usia <= 49:
    print("Dewasa")
else:
    print("Lansia")