# -*- coding: utf-8 -*-
"""Tugas KKA 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ols6Sq0pCtVVxZbJZQhrvJjgpLv-j60K
"""

str_numbers = "456"
str_numbers_to_int = int(str_numbers)
print("Before casting :", str_numbers, ", the data type is",
type(str_numbers))
print("After casting :", str_numbers_to_int, ", the data type is",
type(str_numbers_to_int))

integer = 12345
integer_to_str = str(integer)
print("Before casting :", integer, ", the data type is", type(integer))
print("After casting :", integer_to_str, ", the data type is",
type(integer_to_str))

num_int = 1
num_bool = bool(num_int)
print(num_bool, type(num_bool))
num_int = 0

num_bool = bool(num_int)
print(num_bool, type(num_bool))

# Equal to
8 == 8
# Not equal to
8 != 9
# Greater than
8 > 9
# Less than
8 < 9
# Less than
8 <= 9
# Less than
9 >= 9

a = True
b = True
print(a and b)
print(a or b)
print(not b)
#logic
5 > 6 and 6 < 7

e = 8
f = 2
# Summation
sum = e + f
print(f"The sum of e with f is : {sum}\n")
# Reduction
red = e - f
print(f"The reduction of e with f is : {red}\n")

# Multiplication
multi = e * f
print(f"The multipication of e with f is : {multi}\n")
# Division
divi = e / f
print(f"The quotient of e with f is : {divi}\n")
# Modulo
mod = e % f
print(f"The remainder of e with f is : {mod}\n")
# Power
pow = e ** f
print(f"The power of e of f is : {pow}\n")

name = str(input("What is your name : "))
age = int(input("What's your age : "))
print("Name: ", name)
print("Age: ", age)

print("===== Normal Print =====")
print("Hi all! I am", name, "age", age, "years old")

print("\n===== f-string Print (Rekomendasi) =====")
print(f"Hi all! I am {name} age {age} years old")

print("\n===== % Format Print =====")
print("Hi all! I am %s age %d years old" % (name, age))

print("\n===== Format Output =====")
print(30 * "-")
print("      Welcome to My Program")
print(30 * "-")

try:
    your_GPA = float(input("Enter your GPA: "))

    if 4.0 >= your_GPA >= 3.80:
        print(f"Damn! You've got a Magna Cum Laude with your {your_GPA} GPA")
    elif 3.50 <= your_GPA < 3.80:
        print(f"Cool!! You've got a Cum Laude with your {your_GPA} GPA")
    elif 3.00 <= your_GPA < 3.50:
        print(f"You've got a stable GPA tho ({your_GPA})")
    elif your_GPA < 3.00 and your_GPA >= 0.0:
        print(f"You need a stable GPA (Your GPA: {your_GPA})")
    else:
        print(f"Sorry, your GPA {your_GPA} is out of range and invalid")

except:
    print("Please enter a valid GPA (numbers only)")

a = 3
b = "Even Numbers" if a % 2 == 0 else "Odd Numbers"
print(b)

for i in range(5):
    print(i)
0
1
2
3
4
# For loop with range
for i in range(5):
    print("Data science is easy!")
print(50 * "-")

for i in range(1, 5, 2):
    print("Data science is easy!")

word = "I want to master data science"
for letter in word:
    print(letter)

for m, n in enumerate(word):
        print(f"Index {m}. {n}")

for i in range(5,1,-1):
           print("I want big data's")

for i in range(5):
    if i == 2:
        continue  # skip iteration when i = 2
    if i == 4:
        break  # stop the loop when i = 4
    print(i)

count = 0
while count < 4:
       print("Keep the spirits up interns!")
count += 1